=== MrRamire2/LenguajeDeMarcas/Ud3/xml/Unidad_3_pack_6_Jhonatan_Andres_Ramirez/ejercicio6.3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="tipoPrecio">
  <xs:restriction base="xs:decimal">
    <xs:totalDigits value="6"/>
    <xs:fractionDigits value="2"/>
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="filtro">
   <xs:simpleContent>
     <xs:extension base="tipoPrecio">
       <xs:attribute name="precioMinimo" type="tipoPrecio"/>
     </xs:extension>
   </xs:simpleContent>
</xs:complexType>

  <xs:element name="objetos">
    <xs:complexType>
      <xs:sequence>
      
        <xs:element name="objeto" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="propietario" type="xs:string"/>
              <xs:element name="objetoNombre" type="xs:string"/>
              <xs:element name="precioSalida" type="filtro"/>

            </xs:sequence>
            <xs:attribute name="num" type="xs:integer"/>
          </xs:complexType>
        </xs:element>
        
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MrRamire2/LenguajeDeMarcas/Ud3/xml/Unidad_3_pack_6_Jhonatan_Andres_Ramirez/ejercicio6.3.xml
<?xml version="1.0" encoding="UTF-8"?>
<objetos
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="ejercicio6.3.xsd">
  <objeto>
    <propietario>Jhonatan</propietario>
    <objetoNombre>coche</objetoNombre>
    <precioSalida precioMinimo="2000">1000</precioSalida>
  </objeto>
  <objeto>
    <propietario>Andres</propietario>
    <objetoNombre>bolso</objetoNombre>
    <precioSalida>100</precioSalida>
  </objeto>
</objetos>
