=== MrRamire2/LenguajeDeMarcas/Ud3/xml/Unidad_3_pack_6_Jhonatan_Andres_Ramirez/ejercicio6.4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="empleados">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="empleado" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="info">
                <xs:complexType>
                  <xs:attribute name="nombre" type="xs:string"/>
                  <xs:attribute name="id" type="xs:integer"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="fechaContrato">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="dia" type="xs:gDay"/>
                    <xs:element name="mes" type="xs:gMonth"/>
                    <xs:element name="aÃ±o" type="xs:gYear"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="puestos">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="puesto" type="xs:string"/>
                    <xs:element name="puestosOcupados" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="jefeDirecto">
                <xs:complexType>
                  <xs:attribute name="id"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="sueldo" type="xs:decimal"/>
              <xs:element name="titulos" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="titulo" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="sede">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Madrid"/>
                    <xs:enumeration value="Barcelona"/>
                    <xs:enumeration value="Valencia"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="observaciones" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="meritos" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="demeritos" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MrRamire2/LenguajeDeMarcas/Ud3/xml/Unidad_3_pack_6_Jhonatan_Andres_Ramirez/ejercicio6.4.xml
<?xml version="1.0" encoding="UTF-8"?>
<empleados
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="ejercicio6.4.xsd">
  <empleado>
    <info nombre="Carlos" id="1"></info>
    <fechaContrato>
      <dia>---20</dia>
      <mes>--12</mes>
      <año>2023</año>
    </fechaContrato>
    <puestos>
      <puesto>gerente</puesto>
      <puestosOcupados>oficial</puestosOcupados>
    </puestos>
    <jefeDirecto id="3"/>
    <sueldo>2500</sueldo>
    <titulos>
      <titulo>ingeniero</titulo>
      <titulo>master</titulo>
    </titulos>
    <sede>Madrid</sede>
    <observaciones>
      <demeritos>es to pesao</demeritos>
    </observaciones>
  </empleado>

  <empleado>
    <info nombre="Maria" id="2"></info>
    <fechaContrato>
      <dia>---14</dia>
      <mes>--08</mes>
      <año>2020</año>
    </fechaContrato>
    <puestos>
      <puesto>maquinista</puesto>
    </puestos>
    <jefeDirecto id="1"/>
    <sueldo>1500</sueldo>
    <sede>Barcelona</sede>
    <observaciones>
      <meritos>existir</meritos>
    </observaciones>
  </empleado>

  <empleado>
    <info nombre="Jhonatan" id="3"></info>
    <fechaContrato>
      <dia>---19</dia>
      <mes>--11</mes>
      <año>2022</año>
    </fechaContrato>
    <puestos>
      <puesto>jefe</puesto>
      <puestosOcupados>gerente</puestosOcupados>
    </puestos>
    <jefeDirecto id="3"/>
    <sueldo>3000</sueldo>
    <titulos>
      <titulo>diseñador grafico</titulo>
      <titulo>programador</titulo>
    </titulos>
    <sede>Valencia</sede>
  </empleado>

  <empleado>
    <info nombre="Lina" id="4"></info>
    <fechaContrato>
      <dia>---20</dia>
      <mes>--12</mes>
      <año>2021</año>
    </fechaContrato>
    <puestos>
      <puesto>gerente</puesto>
    </puestos>
    <jefeDirecto id="3"/>
    <sueldo>2800</sueldo>
    <titulos>
      <titulo>ingeniero</titulo>
    </titulos>
    <sede>Barcelona</sede>
    <observaciones>
      <meritos>premio por excelencia</meritos>
    </observaciones>
  </empleado>

  <empleado>
    <info nombre="Melany" id="5"></info>
    <fechaContrato>
      <dia>---15</dia>
      <mes>--01</mes>
      <año>2021</año>
    </fechaContrato>
    <puestos>
      <puesto>subGerente</puesto>
    </puestos>
    <jefeDirecto id="4"/>
    <sueldo>2300</sueldo>
    <titulos>
      <titulo>medico</titulo>
    </titulos>
    <sede>Valencia</sede>
    <observaciones>
      <meritos>premio nobel</meritos>
    </observaciones>
  </empleado>
</empleados>
