=== MrRamire2/LenguajeDeMarcas/Ud3/xml/Unidad_3_pack_2_Jhonatan_Andres_Ramirez/ejercicio2.3.dtd
<!ELEMENT pedidos (tractor+)>
<!ELEMENT tractor (componentes+)>
<!ELEMENT componentes (nombre_fabricante, fecha_entrega, fragil, peso, numero_serie, km_max?)>
<!ELEMENT nombre_fabricante (#PCDATA)>
<!ELEMENT fecha_entrega (dia?, mes, anio)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT fragil (#PCDATA)>
<!ELEMENT peso (#PCDATA)>
<!ELEMENT numero_serie (#PCDATA)>
<!ELEMENT km_max (#PCDATA)>
<!ATTLIST peso unidad CDATA #REQUIRED>

=== MrRamire2/LenguajeDeMarcas/Ud3/xml/Unidad_3_pack_2_Jhonatan_Andres_Ramirez/ejercicio2.3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE pedidos SYSTEM "ejercicio2.3.dtd">

<pedidos>
  <tractor>
    <componentes>
      <nombre_fabricante>JAR</nombre_fabricante>
      <fecha_entrega>
        <dia>12</dia>
        <mes>11</mes>
        <anio>2023</anio>
      </fecha_entrega>
      <fragil>si</fragil>
      <peso unidad="kilos">230</peso>
      <numero_serie>124325234</numero_serie>
      <km_max>12</km_max>
    </componentes>
  </tractor>
  <tractor>
    <componentes>
      <nombre_fabricante>PartesMg</nombre_fabricante>
      <fecha_entrega>
        <mes>04</mes>
        <anio>2023</anio>
      </fecha_entrega>
      <fragil>no</fragil>
      <peso unidad="gramos">200</peso>
      <numero_serie>233464576457</numero_serie>
    </componentes>
  </tractor>
</pedidos>
