=== MrRamire2/LenguajeDeMarcas/Ud3/xml/Unidad_3_pack_5_Jhonatan_Andres_Ramirez/ejercicio5.6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="fitxes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="fitxa" maxOccurs="unbounded">
          <xs:complexType>
            <xs:all>
              <xs:element name="nom" type="xs:string"/>
              <xs:element name="inicials">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Z, a-z][A-Z, a-z][A-Z, a-z]"/><!--se debe añadir la opción letras minúsculas-->
                    <xs:pattern value="[A-Z, a-z][A-Z, a-z]"/>  <!--se debe añadir la opción de dos letras-->
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="edat" type="xs:integer"/>
            </xs:all>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MrRamire2/LenguajeDeMarcas/Ud3/xml/Unidad_3_pack_5_Jhonatan_Andres_Ramirez/ejercicio5.6.xml
<?xml version="1.0" encoding="UTF-8"?>
<fitxes
  xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
  xs:noNamespaceSchemaLocation="ejercicio5.6.xsd">
  <fitxa>
    <nom>Antonio Machado Ruiz</nom>
    <inicials>AMR</inicials>
    <edat>22</edat>
  </fitxa>
  <fitxa>
    <nom>Mario Moreno</nom>
    <inicials>MM</inicials>
    <edat>23</edat>
  </fitxa>
  <fitxa>
    <inicials>ALO</inicials>
    <nom>Ada Lovelace</nom>
    <edat>24</edat>
  </fitxa>
  <fitxa>
    <nom>pablo ruiz picasso</nom>
    <inicials>prp</inicials>
    <edat>24</edat>
  </fitxa>
</fitxes>
