=== MrRamire2/LenguajeDeMarcas/Ud3/xml/Unidad_3_pack_4_Jhonatan_Andres_Ramirez/ejercicio4.2.dtd
<!ELEMENT lista_cursos (cursos+)>
<!ELEMENT cursos (alumnos+)>
<!ELEMENT alumnos (dni, nombre, apellido, segundo_apellido?, asignaturas+)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT segundo_apellido (#PCDATA)>
<!ELEMENT asignaturas (nombre, profesor)>
<!ELEMENT profesor (nrp, nombre, apellido, segundo_apellido?)>
<!ELEMENT nrp (#PCDATA)>
<!ATTLIST asignaturas codigo CDATA #REQUIRED>

=== MrRamire2/LenguajeDeMarcas/Ud3/xml/Unidad_3_pack_4_Jhonatan_Andres_Ramirez/ejercicio4.2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE lista_cursos SYSTEM "ejercicio4.2.dtd">
<lista_cursos>
  <cursos>
    <alumnos>
      <dni>23423423</dni>
      <nombre>Jhonatan</nombre>
      <apellido>Ramirez</apellido>
      <segundo_apellido>Posada</segundo_apellido>
      <asignaturas codigo="2344543234">
        <nombre>Matem√°ticas</nombre>
        <profesor>
          <nrp>234235</nrp>
          <nombre>Julio</nombre>
          <apellido>Cardona</apellido>
        </profesor>
      </asignaturas>
    </alumnos>
  </cursos>
</lista_cursos>
