=== MrRamire2/LenguajeDeMarcas/Ud3/xml/Unidad_3_pack_4_Jhonatan_Andres_Ramirez/ejercicio4.4.dtd
<!ELEMENT intercambio (opciones+, futuro+, divisa+, bono+, letra+)>
<!ELEMENT opciones (#PCDATA)>
<!ELEMENT futuro (precio, proviene, producto?, mercado?)>
<!ELEMENT divisa (precio, proviene, nombre, cambio+)>
<!ELEMENT bono (precio, proviene, pais_procedencia, valor_deseado, valor_minimo, valor_maximo)>
<!ELEMENT valor_deseado (#PCDATA)>
<!ELEMENT valor_minimo (#PCDATA)>
<!ELEMENT valor_maximo (#PCDATA)>
<!ELEMENT letra (precio, proviene, interes, pais_emisor)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT proviene EMPTY>
<!ELEMENT producto (#PCDATA)>
<!ELEMENT mercado (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT cambio (#PCDATA)>
<!ELEMENT pais_procedencia (#PCDATA)>
<!ELEMENT interes (#PCDATA)>
<!ELEMENT pais_emisor (Madrid | NewYork | Frankfurt | Tokio)>
<!ELEMENT Madrid EMPTY>
<!ELEMENT NewYork EMPTY>
<!ELEMENT Frankfurt EMPTY>
<!ELEMENT Tokio EMPTY>
<!ATTLIST divisa estable CDATA #IMPLIED>
<!ATTLIST bono estable CDATA #IMPLIED>
<!ATTLIST opciones ciudades ID #REQUIRED>
<!ATTLIST proviene ciudad IDREF #REQUIRED>

=== MrRamire2/LenguajeDeMarcas/Ud3/xml/Unidad_3_pack_4_Jhonatan_Andres_Ramirez/ejercicio4.4.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE intercambio SYSTEM "ejercicio4.4.dtd">
<intercambio>
  <opciones ciudades="Madrid"/>
  <opciones ciudades="NuevaYork"/>
  <opciones ciudades="Frankfurt"/>
  <opciones ciudades="Tokio"/>
  <futuro>
    <precio>160</precio>
    <proviene ciudad="Madrid"></proviene>
    <producto>Tecnolog√≠a</producto>
    <mercado>Japon</mercado>
  </futuro>
  <divisa estable="">
    <precio>125</precio>
    <proviene ciudad="NuevaYork"></proviene>
    <nombre>Street</nombre>
    <cambio>Dolar</cambio>
    <cambio>Euro</cambio>
  </divisa>
  <bono estable="">
    <precio>169</precio>
    <proviene ciudad="Frankfurt"></proviene>
    <pais_procedencia>Mexico</pais_procedencia>
    <valor_deseado>300</valor_deseado>    
    <valor_minimo>200</valor_minimo>
    <valor_maximo>400</valor_maximo>
  </bono>
  <letra>
    <precio>400</precio>
    <proviene ciudad="Tokio"></proviene>
    <interes>10</interes>
    <pais_emisor>
      <Madrid/>
    </pais_emisor>
  </letra>
</intercambio>
