=== MrRamire2/LenguajeDeMarcas/Ud3/xml/Unidad_3_pack_3_Jhonatan_Andres_Ramirez/ejercicio3.1.dtd
<!ELEMENT lista_ventas (venta+)>
<!ELEMENT venta (importe, comprador, vendedor, fecha?, codigo_factura)>
<!ELEMENT importe (#PCDATA)>
<!ELEMENT comprador (#PCDATA)>
<!ELEMENT vendedor (#PCDATA)>
<!ELEMENT fecha (dia, mes, anio)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT codigo_factura (#PCDATA)>

=== MrRamire2/LenguajeDeMarcas/Ud3/xml/Unidad_3_pack_3_Jhonatan_Andres_Ramirez/ejercicio3.1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE lista_ventas SYSTEM "ejercicio3.1.dtd">
<lista_ventas>
  <venta>
    <importe>45345</importe>
    <comprador>Jhonatan</comprador>
    <vendedor>Armando</vendedor>
    <codigo_factura>5345345</codigo_factura>
  </venta>
  <venta>
    <importe>453045</importe>
    <comprador>Carlos</comprador>
    <vendedor>Juan</vendedor>
    <fecha>
      <dia>12</dia>
      <mes>02</mes>
      <anio>2023</anio>
    </fecha>
    <codigo_factura>1345345</codigo_factura>
  </venta>
</lista_ventas>
