=== MrRamire2/LenguajeDeMarcas/Ud3/xml/Unidad_3_pack_3_Jhonatan_Andres_Ramirez/ejercicio3.3.dtd
<!ELEMENT entrega (lote+)>
<!ELEMENT lote (palet+)>
<!ELEMENT palet (numero_cajas, contenido, peso, forma_manipulacion)>
<!ELEMENT numero_cajas (#PCDATA)>
<!ELEMENT contenido (nombre_componente, procedencia*, numero_serie, peso_unidad?, unidad_peso)>
<!ELEMENT nombre_componente (#PCDATA)>
<!ELEMENT procedencia (#PCDATA)>
<!ELEMENT numero_serie (#PCDATA)>
<!ELEMENT peso_unidad (#PCDATA)>
<!ELEMENT unidad_peso (#PCDATA)>
<!ELEMENT peso (#PCDATA)>
<!ELEMENT forma_manipulacion (#PCDATA)>

=== MrRamire2/LenguajeDeMarcas/Ud3/xml/Unidad_3_pack_3_Jhonatan_Andres_Ramirez/ejercicio3.3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE entrega SYSTEM "ejercicio3.3.dtd">
<entrega>
  <lote>
    <palet>
      <numero_cajas>15</numero_cajas>
      <contenido>
        <nombre_componente>tarjetas graficas</nombre_componente>
        <numero_serie>1342323</numero_serie>
        <unidad_peso>kilo</unidad_peso>
      </contenido>
      <peso>2</peso>
      <forma_manipulacion>a mano</forma_manipulacion>
    </palet>
    <palet>
      <numero_cajas>15</numero_cajas>
      <contenido>
        <nombre_componente>tarjetas graficas</nombre_componente>
        <numero_serie>1342323</numero_serie>
        <peso_unidad>pluma</peso_unidad>
        <unidad_peso>kilo</unidad_peso>
      </contenido>
      <peso>2</peso>
      <forma_manipulacion>a mano</forma_manipulacion>
    </palet>
  </lote>
  <lote>
    <palet>
      <numero_cajas>4</numero_cajas>
      <contenido>
        <nombre_componente>Ram</nombre_componente>
        <procedencia>colombia</procedencia>
        <procedencia>Espa√±a</procedencia>
        <numero_serie>1342323</numero_serie>
        <peso_unidad>pluma</peso_unidad>
        <unidad_peso>kilo</unidad_peso>
      </contenido>
      <peso>2</peso>
      <forma_manipulacion>a mano</forma_manipulacion>
    </palet>
  </lote>
</entrega>
